### ISSUE TITLE
Debian unstable/testing support

### ISSUE THREAD

**Issue by anarcat** [cirrax/puppet-libvirt#62]
I am trying to deploy this module in Debian testing, and that doesn't have a "real" "major" version number (e.g. `12`) and instead the codename (`bookworm/sid`) which, obviously, is .. not great. But it's the way things are right now. 

This, obviously, means that the hiera lookups don't work, as it would look for the defaults in `data/Debian/bookworm/sid.yaml`, which looks really wrong.

I'd like to re-propose my idea discussed in #60 and #59 of making `Debian/default.yaml` refer to the current stable and later, and keep version-specific configurations for older releases, which are eventually dropped. I had originally done so in https://github.com/cirrax/puppet-libvirt/pull/60/commits/8b74e825093b4d224f87f3de2a313103baecc441 and this is how #59 is currently setup as well.

could we revisit this idea? :)

_Originally posted by @anarcat in https://github.com/cirrax/puppet-libvirt/issues/60#issuecomment-1226161446_

**Comment by trefzer** [comment]
_and answered in #60 ;) so I repost/adapt it here (removed stuff about architecture specific):_

hm. I have no idea what %{facts.os.release.major} for bookworm or sid is. Can you enlight me ?

Since many modules use %{facts.os.release.major} you have this problem with other modules too !
So you probably need to overwrite the setting in your environment specific hierarchy (like for other modules).

If we make default.yaml to always support the most recent version we each time risk to break an older version (so each time we have to check all old version to include the old value) if a change is needed. So there is less risk to break a older version if we overwrite with a release specific version (this also means less work for review !).
I agree to cleanup supported versions (removing old versions, moving to defaults) from time to time but this is something that should be done increasing the major module version number (which I plan to do soon when my work on removing all the exec statements will success ....).

I think bookworm should already specify 13 for facts.os.release.major. If not it's probably a debian bug. No idea what sid reports (99 ?). So if bookworm reports 13 we could add a 13[|_amd64].yaml file easily (as soon as we think the settings will not change to much anymore). If sid reports 99, we could do that as well with a explanation/comment in the yaml file.

I still think the chosen version is best.

Cheers
Benedikt

**Comment by trefzer** [comment]
Oh just realized:

> This, obviously, means that the hiera lookups don't work, as it would look for the defaults in data/Debian/bookworm/sid.yaml, which looks really wrong.

did you not mean data/Debian/bookworm.yaml or data/Debian/sid.yaml 
having  %{facts.os.release.major} ==  'bookworm/sid' does not make any sense at all (also which would mean you can not distinguish between the two releases).

having a file data/Debian/bookworm.yaml would be an acceptable solution for me (with a comment that it will be removed as soon as version 13 is released).

**Comment by anarcat** [comment]
> hm. I have no idea what %{facts.os.release.major} for bookworm or sid is. Can you enlight me ?

it's the string `bookworm/sid`. you'd expect it would be a number (like `12`), but no. and yes, maybe that's a total clusterfuck of a nightmare, but it's how things are done.

> Since many modules use %{facts.os.release.major} you have this problem with other modules too !

Yeah, it's been an issue with some modules, but this is the one I'm having problems with right now. :)

> So you probably need to overwrite the setting in your environment specific hierarchy (like for other modules).

Yeah, it's how I worked around this.

> did you not mean data/Debian/bookworm.yaml or data/Debian/sid.yaml having %{facts.os.release.major} == 'bookworm/sid' does not make any sense at all

I really *did* mean what I wrote. The actual string reported by facter is `bookworm/sid`, *not* `bookworm`.
 
>  (also which would mean you can not distinguish between the two releases).

this is also true: there is no way to differentiate a system running bookworm from one running sid right now, apart from looking closely at the sources.list. the reason for that is facter reads the version number from `/etc/debian_version` and *that* comes from the `base-files` package, which is first uploaded to unstable, and then migrates to testing. so it's actually the same package in both suites (if all goes well), so it needs to have a string representing both.

interestingly, `lsb_release -a` *can* actually figure out that i'm running bookworm/testing (and not sid/unstable), i'm not sure how it does that, because that information really is not available anywhere but in the sources.list, and it's not reading that.

> having a file data/Debian/bookworm.yaml would be an acceptable solution for me (with a comment that it will be removed as soon as version 13 is released).

i don't think that's possible with the way debian currently handles os-release.

> If we make default.yaml to always support the most recent version we each time risk to break an older version (so each time we have to check all old version to include the old value) if a change is needed. So there is less risk to break a older version if we overwrite with a release specific version (this also means less work for review !). 

I'm not sure I buy that at all. For example, in this specific case, it was clear that `qemu-kvm` was deprecated in bullseye, so I added the shims for the older supported releases. My patch is not breaking any older release, as the behavior for those is unchanged. We're only changing the behavior for the current stable release and newer, which are currently untested.

Now if there are supported releases that are undocumented, that's a specific problem that should also be fixed. But I don't think my patch changes the way older releases are handled, so that doesn't require extra testing or review.

Maybe I'm misunderstanding your objection here?

> I agree to cleanup supported versions (removing old versions, moving to defaults) from time to time but this is something that should be done increasing the major module version number (which I plan to do soon when my work on removing all the exec statements will success ....).

Sure. I don't think I'm dropping any supported version here though...?

> I think bookworm should already specify 13 for facts.os.release.major.

Not to nitpick, but bookworm is slated to be Debian 12, not 13. And I kind of agree with you, but it seems facter doesn't correctly do that right now.

> If not it's probably a debian bug.

I honestly have no idea how Debian could fix this.

> No idea what sid reports (99 ?).

It reports `bookworm/sid`. :)

> So if bookworm reports 13 we could add a 13[|_amd64].yaml file easily (as soon as we think the settings will not change to much anymore). If sid reports 99, we could do that as well with a explanation/comment in the yaml file.

regardless of the mess Debian is in regarding version number, I think there's value in using `default.yml` to mean "current or next stable", because it allows you to workaround problems like this one, which would be very hard to fix otherwise. I also think it makes long term maintenance easier, but we seem to have a strong disagreement on that, so maybe I'm just wrong there. :)

**Comment by anarcat** [comment]
> So your suggestion is either (version 1):
> 
> - name: 'Major Version architecture specific'
>   path: '%{facts.os.name}/%{facts.os.architecture}.yaml'
> - name: 'Major Version'
>   path: '%{facts.os.name}/%{facts.os.release.major}.yaml'
> 
> or (version 2)
> 
> - name: 'Major Version'
>   path: '%{facts.os.name}/%{facts.os.release.major}.yaml'
> - name: 'Major Version architecture specific'
>   path: '%{facts.os.name}/%{facts.os.architecture}.yaml'
> 
> In version 1 we have no simple possibility to support the older Debian versions, because the architecture dependent version
> is always taken before the release (or default.yaml) version.
> 
> In version 2 we will be in troubles the next time the architecture dependent package will be renamed (and the package stays architecture dependent).

oh and for what it's worth, i think *that* argument (we need to bind the architecture with the release number) is a very good one. i think we could work around it by switching default.yml to the current, so we could do something like:

```
 - name: 'Major Version architecture specific'
   path: '%{facts.os.name}/%{facts.os.release.major}/%{facts.os.architecture}.yaml'
 - name: 'Major Version'
   path: '%{facts.os.name}/%{facts.os.release.major}.yaml'
 - name: 'Distribution architecture specific'
   path: '%{facts.os.name}/%{facts.os.architecture}.yaml'
 - name: 'Distribution Name'
   path: '%{facts.os.name}/default.yaml'
```

... that would cover all needed cases, no?

**Comment by trefzer** [comment]
hm. I aggree, that your comment from 25th of august would probably work.

Since I'm very strict on not breaking old installations, I will not introduce architecture specific defaults (which would potentially break an old version without architecture defined).
Since adding a new supported operating system needs adding a yaml file anyway the architecture could be specified with the same patch (which I think makes reviewing easier).

The question about managing/supporting Debian testing and unstable cannot be solved in this module. I strongly think this needs to be done in your' local hiera config.

So at the end of the day I think we should close this issue. Any opposition ?
